name: CI

on:
  # Runs on pushes and pulls targeting the default branch
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run check (check linting, formatting, types)
        run: pnpm check

      - name: Run unit tests
        run: pnpm test:unit

      - name: Build
        run: pnpm build

      - name: Build Storybook for visual regression tests
        run: pnpm build:sb

      - name: Run visual regression tests
        id: visual-regression
        uses: lost-pixel/lost-pixel@v3.22.0

      - name: Save visual regression artifacts
        if: failure() && steps.visual-regression.outcome == 'failure'
        uses: actions/upload-artifact@v4.6.0
        with:
          name: visual-regression
          path: .lostpixel/
          retention-days: 7
