name: CI

on:
  pull_request:
    branches: ['main', 'qa', 'dev']

  workflow_dispatch:

jobs:
  setup:
      name: Setup
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Install pnpm
          uses: pnpm/action-setup@v4
            
        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            node-version: 'lts/*'
            cache: 'pnpm'
            
        - name: Install dependencies
          run: pnpm install

  lint:
    name: Check (linting, formatting, types)
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
          
      - name: Run check
        run: pnpm check

  unit-tests:
    name: Unit Tests
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
          
      - name: Run unit tests
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: pnpm test:unit --reporter=blob --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: .vitest-reports/*
          include-hidden-files: true
          retention-days: 1

  merge-tests-reports:
    if: ${{ !cancelled() }}
    name: Merge Unit Tests Reports
    needs: [unit-tests]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: .vitest-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge reports
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: pnpm test:unit --merge-reports

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
          
      - name: Build
        run: pnpm build
  
  visual-regression-tests:
    name: Visual Regression Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm build:sb:regression

      - name: Run regression tests
        uses: lost-pixel/lost-pixel@v3.22.0
        env:
          LOST_PIXEL_DISABLE_TELEMETRY: 1

      - name: Upload regression tests artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: regression-tests-artifacts
          path: .lostpixel
