name: Visual regression

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm build:sb

      - name: Run visual regression tests
        uses: lost-pixel/lost-pixel@v3.22.0
        env:
          LOST_PIXEL_DISABLE_TELEMETRY: 1
